import {useEffect,useRef,useState} from'react';
import type{Session}from'@supabase/supabase-js';
import{Cloud,Image as ImageIcon,LoaderCircle,LockKeyhole,LogIn,Plus,Trash2,X}from'lucide-react';
import{MEMORY_BUCKET,supabase}from'./supabase';
type Spot={id:string;cloudId?:string;storagePath?:string;title:string;description:string;image?:string;file?:File;builtIn?:boolean};
type Row={id:string;place:string;slot_key:string;title:string;description:string;storage_path:string};
const EMAIL='qiyideguge@gmail.com';
const defaults:Record<string,Spot[]>={印尼之旅:[{id:'j1',title:'酒店走廊',description:''},{id:'j2',title:'旅行团晚餐',description:''},{id:'b1',title:'火山日出',description:''},{id:'b2',title:'下山的路',description:''}],广州:[{id:'g1',title:'第一次见面',description:''},{id:'g2',title:'一起走过的街道',description:''}],长沙:[{id:'c1',title:'旅行住处',description:''},{id:'c2',title:'一起吃过的店',description:''},{id:'c3',title:'发生故事的街道',description:''}]};
const fresh=()=>Object.fromEntries(Object.entries(defaults).map(([p,s])=>[p,s.map(x=>({...x,builtIn:true}))]));
export function AdventureMapEditor(){
 const[place,setPlace]=useState('长沙'),[data,setData]=useState<Record<string,Spot[]>>(fresh),[session,setSession]=useState<Session|null>(null),[editing,setEditing]=useState<Spot|null>(null),[isNew,setIsNew]=useState(false),[busy,setBusy]=useState(true),[notice,setNotice]=useState(''),[email,setEmail]=useState(EMAIL),[target,setTarget]=useState<Spot|null>(null),[password,setPassword]=useState(''),[passwordError,setPasswordError]=useState(false);const hold=useRef<number|null>(null);
 useEffect(()=>{if(location.hash.includes('error=')){setNotice('上一次登录链接已经失效，请重新发送登录邮件。');history.replaceState(null,'',location.pathname+location.search)}supabase.auth.getSession().then(({data})=>{setSession(data.session);setBusy(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);setBusy(false)});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)void load();else setData(fresh())},[session]);
 async function load(){setBusy(true);const{data:rows,error}=await supabase.from('adventure_spots').select('*').order('created_at',{ascending:true});if(error){setNotice('冒险地图云端空间尚未完成初始化。');setBusy(false);return}const next:Record<string,Spot[]>=fresh();for(const row of(rows||[])as Row[]){const{data:signed}=await supabase.storage.from(MEMORY_BUCKET).createSignedUrl(row.storage_path,86400),spot:Spot={id:row.slot_key,cloudId:row.id,storagePath:row.storage_path,title:row.title,description:row.description,image:signed?.signedUrl};if(!next[row.place])next[row.place]=[];const i=next[row.place].findIndex(x=>x.id===row.slot_key);if(i>=0)next[row.place][i]={...spot,builtIn:true};else next[row.place].push(spot)}setData(next);setBusy(false)}
 const needLogin=(fn:()=>void)=>session?fn():setNotice('请先登录授权邮箱，再保存云端内容。');
 const openNew=()=>needLogin(()=>{setIsNew(true);setEditing({id:crypto.randomUUID(),title:'',description:''})}),edit=(s:Spot)=>needLogin(()=>{setIsNew(!s.builtIn&&!s.cloudId);setEditing({...s})});
 const choose=(file?:File)=>{if(!file||!editing)return;if(file.size>15*1024*1024){setNotice('照片不能超过 15MB。');return}setEditing({...editing,file,image:URL.createObjectURL(file)})};
 const login=async()=>{setBusy(true);const normalized=email.trim().toLowerCase();if(normalized!==EMAIL){setNotice('这个邮箱暂未加入访问名单。');setBusy(false);return}const{error}=await supabase.auth.signInWithOtp({email:normalized,options:{emailRedirectTo:'https://qiyizoro.github.io/'}});setNotice(error?`发送失败：${error.message}`:'登录链接已发送，请使用最新邮件中的链接。');setBusy(false)};
 const save=async()=>{if(!session||!editing?.file||!editing.title.trim()){setNotice('请选择照片并填写区域名称。');return}setBusy(true);setNotice('正在保存到云端…');const ext=editing.file.name.split('.').pop()?.toLowerCase()||'jpg',path=`${session.user.id}/adventure/${crypto.randomUUID()}.${ext}`,up=await supabase.storage.from(MEMORY_BUCKET).upload(path,editing.file,{contentType:editing.file.type});if(up.error){setNotice(`照片保存失败：${up.error.message}`);setBusy(false);return}const payload={place,slot_key:editing.id,title:editing.title.trim(),description:editing.description.trim(),storage_path:path},query=editing.cloudId?supabase.from('adventure_spots').update(payload).eq('id',editing.cloudId):supabase.from('adventure_spots').insert(payload),saved=await query.select().single();if(saved.error){await supabase.storage.from(MEMORY_BUCKET).remove([path]);setNotice(`文字保存失败：${saved.error.message}`);setBusy(false);return}if(editing.storagePath)await supabase.storage.from(MEMORY_BUCKET).remove([editing.storagePath]);setEditing(null);setNotice('已保存到云端，其他设备刷新后即可看到。');await load()};
 const cancelHold=()=>{if(hold.current!==null)clearTimeout(hold.current);hold.current=null},askDelete=(s:Spot)=>{if(s.cloudId){setTarget(s);setPassword('');setPasswordError(false)}},startHold=(s:Spot)=>{if(!s.cloudId)return;cancelHold();hold.current=window.setTimeout(()=>{askDelete(s);navigator.vibrate?.(35)},650)};
 const remove=async()=>{if(!target?.cloudId)return;if(password!=='5555'){setPasswordError(true);return}setBusy(true);const{error}=await supabase.from('adventure_spots').delete().eq('id',target.cloudId);if(!error&&target.storagePath)await supabase.storage.from(MEMORY_BUCKET).remove([target.storagePath]);setNotice(error?`删除失败：${error.message}`:'照片与说明已从云端删除。');setTarget(null);await load()};
 return <><section className="adventure-layout"><aside className="place-tabs">{Object.keys(data).map(p=><button key={p} onClick={()=>setPlace(p)} className={place===p?'active':''}><span>⌖</span><div><b>{p}</b><small>{data[p].length} 个区域</small></div></button>)}</aside><div className="place-detail"><p className="eyebrow">已抵达区域</p><h2>{place}</h2><p className="place-intro">这里保存我们在{place}去过的所有地方。图片与说明会同步保存到所有授权设备。</p><div className="adventure-cloud-status"><Cloud size={15}/>{session?`云端同步已开启 · ${session.user.email}`:'登录后开启多设备云端同步'}</div>{notice&&<p className="adventure-notice">{notice}</p>}{!session&&<div className="adventure-login"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/><button className="primary" onClick={login} disabled={busy}><LogIn size={16}/>发送登录链接</button></div>}{busy&&<div className="adventure-busy"><LoaderCircle/>正在同步云端内容…</div>}<div className="spot-grid">{data[place].map(s=><article key={s.id} className="editable-spot" onClick={()=>edit(s)} onTouchStart={()=>startHold(s)} onTouchEnd={cancelHold} onTouchMove={cancelHold}>{s.image?<img className="spot-photo" src={s.image} alt={s.title}/>:<div className="placeholder"><Plus/>添加图片</div>}{s.cloudId&&<button className="spot-delete" onClick={e=>{e.stopPropagation();askDelete(s)}}><Trash2 size={15}/><span>删除</span></button>}<div><p>区域记录</p><h3>{s.title}</h3><span className="spot-description">{s.description||'点击添加照片与文字说明'}</span></div></article>)}</div><button className="add-spot" onClick={openNew}><Plus/> 自主添加照片与文字</button></div></section>{editing&&<div className="editor-backdrop" onMouseDown={()=>setEditing(null)}><section className="spot-editor" onMouseDown={e=>e.stopPropagation()}><button className="editor-close" onClick={()=>setEditing(null)}><X/></button><p className="eyebrow">{isNew?'新增区域记录':'编辑区域记录'}</p><h2>保存一段旅程</h2><label className="image-picker">{editing.image?<img src={editing.image} alt="照片预览"/>:<><ImageIcon/><span>选择一张照片</span></>}<input type="file" accept="image/*" onChange={e=>choose(e.target.files?.[0])}/></label><label>区域名称<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>文字说明<textarea value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})} rows={4}/></label><button className="primary editor-save" onClick={save} disabled={busy||!editing.file}>保存到云端</button></section></div>}{target&&<div className="editor-backdrop" onMouseDown={()=>setTarget(null)}><section className="delete-dialog" onMouseDown={e=>e.stopPropagation()}><LockKeyhole/><p className="eyebrow">受保护操作</p><h2>删除这张旅行照片？</h2><p>删除后，所有设备都会同步移除照片与说明。</p><input autoFocus type="password" inputMode="numeric" maxLength={4} value={password} onChange={e=>{setPassword(e.target.value);setPasswordError(false)}} placeholder="四位密码"/>{passwordError&&<small>密码不正确，请重新输入。</small>}<button className="delete-confirm" onClick={remove}><Trash2 size={16}/>确认删除</button></section></div>}</>}
