import {useEffect,useRef,useState} from'react';import{Camera,Edit3,Plus,Sparkles,Trash2,Upload,X}from'lucide-react';import{MEMORY_BUCKET,supabase}from'./supabase';import ProfileCard from'./ProfileCard';import DomeGallery,{type DomeImage}from'./DomeGallery';import'./CloudProfile.css';
type Meta={bio:string;quote:string;avatarPath?:string;photos:{id:string;path:string;createdAt:string}[]};
const defaults=(name:string):Meta=>({bio:name==='椰椰'?'擅长观察周围，也总能在细小的情绪里找到值得被照顾的部分。她有清醒的逻辑，也保留柔软的直觉。':'记录世界，也记录我们怎样一点点靠近。',quote:name==='椰椰'?'我会按自己的方式，好好感受这个世界。':'想把值得的事情都认真留下来。',photos:[]});
export default function CloudProfile({name,image}:{name:string;image?:string}){const key=`profile-${name==='椰椰'?'yeye':'qiqi'}`,[meta,setMeta]=useState<Meta>(defaults(name)),[avatar,setAvatar]=useState(image||'/images/yeye-avatar.jpg'),[photos,setPhotos]=useState<DomeImage[]>([]),[editing,setEditing]=useState(false),[draft,setDraft]=useState(defaults(name)),[target,setTarget]=useState<DomeImage|null>(null),[password,setPassword]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),avatarInput=useRef<HTMLInputElement>(null),galleryInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{void load()},[]);
 async function signed(path:string){const{data}=await supabase.storage.from(MEMORY_BUCKET).createSignedUrl(path,86400);return data?.signedUrl||''}
 async function load(){const{data}=await supabase.from('site_data').select('value').eq('key',key).maybeSingle();const next=data?.value?{...defaults(name),...(data.value as Meta)}:defaults(name);setMeta(next);setDraft(next);if(next.avatarPath){const url=await signed(next.avatarPath);if(url)setAvatar(url)}const resolved=await Promise.all((next.photos||[]).map(async p=>({id:p.id,path:p.path,src:await signed(p.path),alt:`${name}的人物照片`})));setPhotos(resolved.filter(p=>p.src))}
 async function save(next:Meta){setMeta(next);setDraft(next);const{error}=await supabase.from('site_data').upsert({key,value:next,updated_at:new Date().toISOString()});setNotice(error?`保存失败：${error.message}`:'已保存到云端。')}
 async function upload(file:File,kind:'avatar'|'gallery'){if(!file.type.startsWith('image/')){setNotice('请选择图片文件。');return}if(file.size>15*1024*1024){setNotice('单张图片请不要超过 15MB。');return}setBusy(true);const ext=file.name.split('.').pop()?.toLowerCase()||'jpg',path=`profiles/${name==='椰椰'?'yeye':'qiqi'}/${kind}/${crypto.randomUUID()}.${ext}`,result=await supabase.storage.from(MEMORY_BUCKET).upload(path,file,{contentType:file.type});if(result.error){setNotice(`上传失败：${result.error.message}`);setBusy(false);return}if(kind==='avatar'){const next={...meta,avatarPath:path};await save(next);setAvatar(await signed(path))}else{const item={id:crypto.randomUUID(),path,createdAt:new Date().toISOString()},next={...meta,photos:[...meta.photos,item]};await save(next);await load()}setBusy(false)}
 async function remove(){if(!target)return;if(password!=='5555'){setNotice('密码不正确。');return}setBusy(true);const next={...meta,photos:meta.photos.filter(p=>p.id!==target.id)};await supabase.storage.from(MEMORY_BUCKET).remove(target.path?[target.path]:[]);await save(next);setTarget(null);setPassword('');await load();setBusy(false)}
 const role=name==='椰椰'?'高敏感观察者 · 隐藏身份：魔法少女':'世界记录者 · 长期主义者 · 轨道维护员';
 return <><section className="character-intro"><div><span>PERSONAL ARCHIVE · RESIDENT 01</span><h1>{name}<i>的世界</i></h1><p>关于她的性格、偏爱与不断生长的瞬间。</p></div><div className="archive-index"><b>217</b><small>PRIVATE CELESTIAL FILE</small></div></section><section className="character-sheet"><div className="card-column"><ProfileCard avatarUrl={avatar} name={name} title={role} contactText="更换头像" onContactClick={()=>avatarInput.current?.click()} onAvatarLongPress={()=>avatarInput.current?.click()}/><small className="long-tip">手机长按卡片，可更换头像</small><input ref={avatarInput} hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,'avatar');e.target.value=''}}/></div><article className="profile-copy"><span>01 / CHARACTER NOTE</span><h2>她是一颗<br/><em>柔软而清醒</em>的星。</h2><p>{meta.bio}</p><blockquote>“{meta.quote}”</blockquote><button onClick={()=>{setDraft(meta);setEditing(true)}}><Edit3/> 编辑人物文字</button></article><aside className="profile-facts">{[['身份编号','217—01'],['喜欢','辣味 · 海 · 夜晚'],['特别能力','读懂空气'],['档案状态','持续更新']].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}<Sparkles/></aside></section><section className="gallery-head"><div><span>VISUAL MEMORY DOME</span><h2>她的不同切面</h2><p>拖动穹顶浏览照片，点开一段正在发生的人物档案。</p></div><button disabled={busy} onClick={()=>galleryInput.current?.click()}><Upload/> {busy?'正在保存…':'上传一张照片'}</button><input ref={galleryInput} hidden type="file" accept="image/*" multiple onChange={e=>{[...(e.target.files||[])].forEach(f=>void upload(f,'gallery'));e.target.value=''}}/></section><DomeGallery images={photos} onLongPress={setTarget}/>{notice&&<button className="cloud-notice" onClick={()=>setNotice('')}>{notice}</button>}
 {editing&&<div className="profile-modal-bg" onMouseDown={()=>setEditing(false)}><section onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setEditing(false)}><X/></button><span>EDIT CHARACTER NOTE</span><h2>编辑人物文字</h2><label>人物描述<textarea rows={5} value={draft.bio} onChange={e=>setDraft({...draft,bio:e.target.value})}/></label><label>人物引用<textarea rows={3} value={draft.quote} onChange={e=>setDraft({...draft,quote:e.target.value})}/></label><button className="modal-save" onClick={()=>{void save(draft);setEditing(false)}}>保存到云端</button></section></div>}
 {target&&<div className="profile-modal-bg" onMouseDown={()=>setTarget(null)}><section onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setTarget(null)}><X/></button><Trash2/><h2>删除这张照片？</h2><p>请输入管理密码后删除，其他设备也会同步。</p><input type="password" inputMode="numeric" maxLength={4} placeholder="四位密码" value={password} onChange={e=>setPassword(e.target.value)}/><button className="modal-save danger" disabled={busy} onClick={()=>void remove()}>确认删除</button></section></div>}</>}
