import{useEffect,useRef}from'react';
import{Mesh,Program,Renderer,Triangle}from'ogl';
import'./galaxy.css';
const vertex=`attribute vec2 uv;attribute vec2 position;varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,0.,1.);}`;
const fragment=`precision highp float;uniform float uTime;uniform vec2 uResolution;uniform vec2 uMouse;uniform float uDensity;uniform float uGlow;varying vec2 vUv;
float hash(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}
float star(vec2 p,float flare){float d=length(p);float m=.025*uGlow/max(d,.002);m+=smoothstep(.01,0.,abs(p.x*p.y))*flare*.18;m*=smoothstep(.5,.06,d);return m;}
vec3 layer(vec2 uv,float seed){vec3 col=vec3(0.);vec2 gv=fract(uv)-.5,id=floor(uv);for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++){vec2 o=vec2(float(x),float(y)),cell=id+o;float n=hash(cell+seed),size=fract(n*345.32),tw=.7+.3*sin(uTime*(.4+n)+n*23.);vec2 drift=vec2(sin(uTime*.08+n*12.),cos(uTime*.06+n*9.))*.12;float s=star(gv-o-drift,smoothstep(.92,1.,size))*size*tw;col+=s*mix(vec3(.58,.72,.9),vec3(1.,.78,.48),hash(cell+8.));}return col;}
void main(){vec2 uv=(vUv*uResolution-.5*uResolution)/uResolution.y;vec2 mp=(uMouse*uResolution-.5*uResolution)/uResolution.y;float md=length(uv-mp);uv+=(uv-mp)*.018/(md+.12);float a=uTime*.018;uv=mat2(cos(a),-sin(a),sin(a),cos(a))*uv;vec3 col=vec3(0.);for(float i=0.;i<4.;i++){float depth=fract(i*.25+uTime*.018);float scale=mix(18.*uDensity,2.2*uDensity,depth);col+=layer(uv*scale+i*83.1,i*37.2)*depth*(1.-depth)*4.;}float haze=max(0.,.12-length(uv)*.11);col+=vec3(.05,.12,.2)*haze;gl_FragColor=vec4(col,min(1.,length(col)*1.8));}`;
export default function Galaxy(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const host=ref.current;if(!host)return;const renderer=new Renderer({alpha:true,premultipliedAlpha:false,dpr:Math.min(devicePixelRatio,1.5)}),gl=renderer.gl;gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);const mouse=new Float32Array([.5,.5]),program=new Program(gl,{vertex,fragment,transparent:true,uniforms:{uTime:{value:0},uResolution:{value:new Float32Array([1,1])},uMouse:{value:mouse},uDensity:{value:1.25},uGlow:{value:.75}}}),mesh=new Mesh(gl,{geometry:new Triangle(gl),program});let frame=0;const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);program.uniforms.uResolution.value[0]=gl.canvas.width;program.uniforms.uResolution.value[1]=gl.canvas.height},move=(e:PointerEvent)=>{const r=host.getBoundingClientRect();mouse[0]=(e.clientX-r.left)/r.width;mouse[1]=1-(e.clientY-r.top)/r.height},draw=(t:number)=>{program.uniforms.uTime.value=t*.001;renderer.render({scene:mesh});frame=requestAnimationFrame(draw)};resize();host.appendChild(gl.canvas);addEventListener('resize',resize);host.addEventListener('pointermove',move);frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize);host.removeEventListener('pointermove',move);gl.canvas.remove();gl.getExtension('WEBGL_lose_context')?.loseContext()}},[]);return <div className="galaxy-container" ref={ref}/>}
